/********************************* 
 * Author: John Alejandro Bedoya *
 * Date:   04/2022               *
 * Description: Test Xervica     *
 ********************************/
@isTest
public class OpportunityWonAndClose_Controller_Test {

    @isTest static void OpportunityWonAndCloseControllerTest(){
        
        Test.startTest();
        
        OpportunityWonAndClose_Controller.listValues(null);
           
        Test.stopTest();    
    }
}